{{- if .Values.logstash.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
{{- end }}