# NOTE: The commented-out values with "REPLACE-ME" must be supplied via helm --set if not provided here
# Please don't commit them to version control.

invenio:
    init: true  # initiates db, index, and admin roles
    hostname: "mex-invenio.azure.cottagelabs.com"
    #secret_key: "REPLACE-ME"
    #security_login_salt: "REPLACE-ME"
    #csrf_secret_salt: "REPLACE-ME"
    create_fixtures: true
    extraConfig:
      INVENIO_MAIL_SERVER: "sandbox.smtp.mailtrap.io"
      INVENIO_MAIL_PORT: "2525"
      INVENIO_MAIL_USERNAME: "REPLACE-ME"
      INVENIO_MAIL_PASSWORD: "REPLACE-ME"
      INVENIO_MAIL_USE_SSL: "False"
      INVENIO_MAIL_USE_TLS: "True"
      INVENIO_SETTINGS_MODULE: "mex_invenio.config"
    datacite:
      enabled: false
web:
  image: "cottagelabs.azurecr.io/mex-invenio:latest"
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  resources:
    requests:
      cpu: 750m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

worker:
  image: "cottagelabs.azurecr.io/mex-invenio:latest"
  livenessProbe:
    initialDelaySeconds: 120

persistence:
  enabled: true
  storage_class: "azure-invenio-storage-class"

haproxy:
  enabled: false

flower:
  enabled: false

#rabbitmq:
#    auth:
#      password: "REPLACE-ME"

#postgresql:
#    auth:
#      password: "REPLACE-ME"

ingress:
  enabled: true
  class: "webapprouting.kubernetes.azure.com"
  tlsSecretNameOverride: "invenio-letsencrypt-secret"
  annotations:
    kubernetes.io/ingress.class: "webapprouting.kubernetes.azure.com"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: "50G"

clusterissuer:
  email: "sysadmin+mex@cottagelabs.com"
