---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "invenio-assets-claim"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "{{ .Values.volume.assets.size }}"
  storageClassName: "manilabronze"
