---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: 'http'
    port: 80
    targetPort: 8080
  selector:
    app: nginx
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: TZ
          value: "Europe/Zurich"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
          - name: var-run
            mountPath: /var/run
          - name: var-cache-nginx
            mountPath: /var/cache/nginx
          - name: var-log-nginx
            mountPath: /var/log/nginx
          - name: static
            mountPath: /static
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
      {{ if .Values.logstash.enabled }}
      - name: filebeat
        image: {{ .Values.logstash.filebeat_image }}
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: var-log-nginx
          mountPath: /var/log/nginx
          readOnly: true
      {{ end }}
      volumes:
      {{ if .Values.logstash.enabled }}
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      {{ end }}
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: var-run
        emptyDir: {}
      - name: var-cache-nginx
        emptyDir: {}
      - name: var-log-nginx
        emptyDir: {}
      - name: static
        emptyDir: {}

{{ if .Values.logstash.enabled }}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "filebeat" 
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "ImageChange"
  source: 
    dockerfile: |
      FROM docker.elastic.co/beats/filebeat-oss:7.6.1
      USER root
      RUN chgrp -R 0 /usr/share/filebeat && \             
      chmod -R o=rx /usr/share/filebeat
      RUN chown -R root:root /usr/share/filebeat
                  
  strategy: 
    dockerStrategy:
      type: Docker
  output: 
    to:
      kind: "ImageStreamTag"
      name: "filebeat:latest"
---
kind: "ImageStream"
apiVersion: "image.openshift.io/v1"
metadata:
  name: "filebeat"
spec:
  tags:
  - name: "latest"
{{ end }}