---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "invenio.fullname" . }}-config
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
data:
  {{- include "invenio.mergeConfig" . | nindent 2 -}}
