{{- if or (not .Values.invenio.existing_secret) (not .Values.invenio.existingSecret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: invenio-secrets
  labels:
    app: invenio-secrets
    {{- include "invenio.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  INVENIO_SECRET_KEY: {{ randAlphaNum 128 | b64enc | quote }}
  INVENIO_SECURITY_LOGIN_SALT: {{ randAlphaNum 128 | b64enc | quote }}
  INVENIO_SECURITY_PASSWORD_SALT: {{ randAlphaNum 128 | b64enc | quote }}
  INVENIO_SECURITY_CONFIRM_SALT: {{ randAlphaNum 128 | b64enc | quote }}
  INVENIO_SECURITY_RESET_SALT: {{ randAlphaNum 128 | b64enc | quote }}
  INVENIO_SECURITY_CHANGE_SALT: {{ randAlphaNum 128 | b64enc | quote }}
  INVENIO_SECURITY_REMEMBER_SALT: {{ randAlphaNum 128 | b64enc | quote }}
  INVENIO_CSRF_SECRET_SALT: {{ randAlphaNum 128 | b64enc | quote }}
{{- end -}}
