{{- if not (or .Values.invenio.existing_secret .Values.invenio.existingSecret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "invenio.secretName" . }}
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  # retrieve the secret data to avoid creating one on every deployment
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace ( include "invenio.secretName" . )) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  INVENIO_SECRET_KEY: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_SECRET_KEY") | quote }}
  INVENIO_SECURITY_LOGIN_SALT: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_SECURITY_LOGIN_SALT") | quote }}
  INVENIO_SECURITY_PASSWORD_SALT: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_SECURITY_PASSWORD_SALT") | quote }}
  INVENIO_SECURITY_CONFIRM_SALT: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_SECURITY_CONFIRM_SALT") | quote }}
  INVENIO_SECURITY_RESET_SALT: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_SECURITY_RESET_SALT") | quote }}
  INVENIO_SECURITY_CHANGE_SALT: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_SECURITY_CHANGE_SALT") | quote }}
  INVENIO_SECURITY_REMEMBER_SALT: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_SECURITY_REMEMBER_SALT") | quote }}
  INVENIO_CSRF_SECRET_SALT: {{ default (randAlphaNum 128 | b64enc ) (get $secretData "INVENIO_CSRF_SECRET_SALT") | quote }}
{{- end -}}
