---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "invenio.fullname" . }}-web
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
    app.kubernetes.io/component: web

  {{- if .Values.web.annotations }}
  annotations: {{- toYaml .Values.web.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: 'http'
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/component: web
  type: {{ .Values.web.service.type }}
